### ISSUE TITLE
Production npm package

### ISSUE THREAD

**Issue by Arteneko** [getmeli/meli#1]
Could we expect a production-ready npm package?

Managing a production setup manually using git / npm not only pulls lots of bloat (e.g. development tools for building the optimized version, the entire `.git` tree, etc.), but is also cumbersome in environment and paths management, whereas a well-setup nodejs environment can provide binaries in the path with just an `npm i -g ...`.

**Comment by pimartin** [comment]
We're currently focusing on the Docker deployment as we believe it is the easiest for the users (the interaction between Caddy and Meli requires configuration that would deter a lot of users and be prone to many errors) and we have a big (and growing) todo list.

But we will probably add a Dockerless deployment in the future and a npm package would certainly be the way to go.

**Comment by gempain** [comment]
@Arteneko for fully featured platforms with dependencies like ours, it is generally easier to deploy with Docker as there is a lot of configuration taken off your shoulders. I would like to see a Dockerless deployment in the future, so we'll add this to our roadmap, but there are other things we would love to achieve before getting there. I am not too familiar with Dockerless deployments as it's something we have not done for the past couple of years, so I would love to see the community submit a PR for this. I will happily make myself available to help if necessary.

**Comment by gempain** [comment]
We're focused on supporting the Docker deployment because we believe it's the most efficient way to deploy. Dependencies like Mongo and Caddy would require much more work to setup without using Docker, and I don't see a case where you would manage your Caddy and Mongo dependencies with Docker but deploy Meli with Npm. Hence, we have decided to close this issue so we can focus on our roadmap. This doesn't mean we don't want this to happen, but it means that we haven't seen enough traction for it at this time.
