### ISSUE TITLE
Custom domains don't work for branch deploys

### ISSUE THREAD

**Issue by queicherius** [getmeli/meli#165]
I have setup DNS records (A) for `project.company.io` and `*.project.company.io`, pointing at the Meli IP.

I then added `project.company.io` into the "Domains" section of the site settings. This now works perfectly for `project.company.io` itself, pointing towards the main branch.

However, if I call `branch.project.company.io`, I get a `ERR_SSL_PROTOCOL_ERROR`, with a "no server TLS configuration available" error.

This is fixable, if I add `*.project.company.io` to the domains in the site settings, but I feel like this either requires some docs or should happen automatically.

**Comment by pimartin** [comment]
The original goal for the custom domains was to set the "production" domain for the site while the original goal for the branches was to allow the preview of the "non-prod" versions (beta, demo...). Which is why it is currently not working correctly.

It does however make sense to add the branches to the custom domains in certain cases.

So we're going to:
  - add a toggle to enable/disable branches on a custom domain
  - if enabled:
    - add the subdomains to the SSL configuration
    - add the subdomains to the routes (this happens unconditionally at this time)
  - (add validation on the domain name setting to prevent the use of wildcard domains?)
  - improve/update the documentation to reflect this change

After this change, the user will need to:
  - specify its domains without wildcard in the settings (`project.company.io`)
  - enable the branches for the domain
  - add a wildcard entry in the DNS zone (`*.project.company.io`)

**Comment by gempain** [comment]
@queicherius so sorry it took this long to get on this, but I'm on it 😄

**Comment by gempain** [comment]
This has been implemented and will be included in the next release. A toggle under your custom domains will allow you to toggle branches for subdomains. I believe this is a breaking change with your current workaround.

![Screen Shot 2021-01-12 at 14 31 15](https://user-images.githubusercontent.com/13135149/104320631-dc484d00-54e2-11eb-9798-a3f6757747d6.png)

**Comment by gempain** [comment]
@queicherius i'm closing, but please let me know if further help is needed, happy to help 😀
