### ISSUE TITLE
Clarify that it is not open-source

### ISSUE THREAD

**Issue by bradp** [getmeli/meli#171]
The README states 'open-source' but the license clearly states `The Business Source License  is not an Open Source license.`

**Comment by gempain** [comment]
@bradp the words "Open Source" in our README refer to the definition given by many well-recognized dictionaries of various languages, which is "used to describe software for which the original source code is made available to anyone".

The words "Open Source" in our license, introduced and written by MariaDB, refer to the definition given by the Open Source Foundation. Though we adopted this license to make it easier for users to recognize it, we disagree with this sentence being part of it and are working on this matter.

The BSL license allows you to modify, share, redistribute and use this software for free with the only condition that you do not run a competing SAAS service based on this project, which would both be unfair and jeopardize the options of making this tool sustainable.

We chose the BSL license because we believe it is fair for both users and maintainers. It allows us to secure a monetization path while providing proper support in the long run. Also, our license converts automatically within 4 years of each release to a license officially recognized by the Open Source Foundation, which secures a way for the community to see the sole restriction removed.

We are aware of the debate around the BSL conflicting with rule number 9 of the definition given by the Open Source Foundation. We do believe that, in specific cases, this rule should be relaxed as it prevents platform maintainers to secure a path to sustaining the development of their tool and support of their community while preventing large players from running unfair competition by leveraging their infrastructure and name. There is sufficient material on this matter available on the internet for users to make up their mind.

As a side note, rule number 9 conflicts similarly with the BSL than with the GPL3.0, which does restrict the creation of other software in its own way, while still being officially recognized by the Open Source Foundation.

We will add a section in our README to clarify things. However, as we do believe this project **is** open-source given the definition from well-recognized dictionaries of various languages, we can only clarify how it **is** open source, not how it **isn't** per your request.

**Comment by konsalex** [comment]
Hey @gempain, while reading the license clause, I still find it a little confusing on what it needs to run on production without causing a legal issue 🤔 

`The BSL license allows you to modify, share, redistribute and use this software for free with the only condition that you do not run a competing SAAS service based on this project, which would both be unfair and jeopardize the options of making this tool sustainable.`

This means that it is more than fine to use Meli in production, if and only if we don't run a competing SaaS service right?

**Comment by gempain** [comment]
Hi there 👋 you can absolutely run Meli in production, as you rightly said, given that you don't run a competing SAAS service. To be a bit more clear, Meli's obvious way to support the project is to sell subscriptions for hosting sites. The notion of "competing SAAS service" may seem a bit blurry. If you are a website designer or web design company, it's perfectly fine to use Meli to host demos or even host production sites for your customers. The same is true for your personal projects. However, if the only service you sell is hosting a site for your customers with Meli, and you have tens, hundreds or thousand of customers, I would consider this a competing SAAS. There are gray areas and this license is far from perfect but we expect people to have common sense for what can be considered compliant with it. When in doubt, I'm happy to have a chat about your specific use case privately (you should be able to message me through Twitter @gempain) 🙂

**Comment by konsalex** [comment]
Thanks @gempain for the explanation. Will definitely then try out and provide some feedback soon 🚀

**Comment by gempain** [comment]
Very welcome, happy to help ! Enjoy using Meli 🚀
