### ISSUE TITLE
Gitlab Docs are Wrong

### ISSUE THREAD

**Issue by mtiller** [getmeli/meli#243]
The documentation on using Gitlab say that the `scope` required is `api`.  But, in fact, the scope required is `read_api`.

Furthermore, the instructions are confusing because they don't explain what `MELI_GITLAB_URL` should point to.  As far as I can tell, they should point to the URL for your Gitlab instance.  In my case, that is `https://gitlab.com` but in the example it references an IP address and very odd port (`3003`) which is very confusing.

My configuration seems to work.  I'd gladly submit a PR for the docs if someone would indicate that such a PR would be accepted and they could point me to where they are (a cursory glance at the repo didn't turn up anything).  But in any case, hopefully this issue can help someone else at a minimum.

Thanks.

**Comment by gempain** [comment]
@mtiller hi 👋  and thanks for reporting this ! Indeed, the docs seem to be using an IP instead of a URL, we most likely missed it. While `read_api` may work, we've always used the broader scope `api` and haven't tested Gitlab integration with a lower access scope, but I'm glad it's working with that config.

A PR would be more than welcome, thanks so much for offering ! We've got a very handy "Edit this page" link at the bottom of each docs page, which should open the source Markdown file right here on Github, ready to be patched.

<img width="546" alt="Screenshot 2022-02-01 at 00 43 13" src="https://user-images.githubusercontent.com/13135149/151891301-8d9fa706-ba56-4bed-a949-24c71a175ff1.png">

Just in case, here is the link for editing the page you are referring to: https://github.com/getmeli/meli-docs/edit/latest/docs/authentication/gitlab.md

**Comment by gempain** [comment]
Closing as your MR has been merged. Thanks so much !
