### ISSUE TITLE
No way to define redirects for Single Page Applications

### ISSUE THREAD

**Issue by ayush123460** [getmeli/meli#5]
As the title suggests, there's no way to define redirects for single page applications, at least none as per the documentation. This can be implemented by specifying a file with a rewrite rule.

**Comment by gempain** [comment]
@ayush123460 this is possible, but not as you describe. At the moment, you can specify a redirect of type `reverse_proxy` and point to `your-site.mymeli.com`, but I'll agree it's not ideal for your use case. I'll get right on it and add this in the next release.

To summarize the changes, we'll be adding a new type of redirect with the following settings:
- the path
- the redirect URI

**Comment by devlopesbernardo** [comment]
That's awesome - ping if in need of any further help :metal:

**Comment by gempain** [comment]
@devlopesbernardo after more thinking, instead of a new redirect type, we will add a toggle under site settings to enable SPA mode, as this is something you don't need to configure specifically, it's basically the same for all SPAs. It'll make things easier for everyone.

**Comment by gempain** [comment]
@devlopesbernardo this feature was released in v1.0.0-beta.5. You'll now be able to enable SPA mode in your site settings. I'm closing, but you may continue to reply if further help is required. We'll reopen if needed. Again, many thanks for contributing to this project (I do see issues as contributions because you take the time to open them).
